//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.PilotHelmet
{
    [Serializable]
    public class HandSkeletonMsg : Message
    {
        public const string k_RosMessageName = "pilot_helmet/HandSkeleton";
        public override string RosMessageName => k_RosMessageName;

        public TimeMsg timestamp;
        public Geometry.TransformMsg head;
        public Geometry.TransformMsg wrist_root;
        public Geometry.TransformMsg forearm_stub;
        public Geometry.TransformMsg thumb0;
        public Geometry.TransformMsg thumb1;
        public Geometry.TransformMsg thumb2;
        public Geometry.TransformMsg thumb3;
        public Geometry.TransformMsg thumb_tip;
        public Geometry.TransformMsg index1;
        public Geometry.TransformMsg index2;
        public Geometry.TransformMsg index3;
        public Geometry.TransformMsg index_tip;
        public Geometry.TransformMsg middle1;
        public Geometry.TransformMsg middle2;
        public Geometry.TransformMsg middle3;
        public Geometry.TransformMsg middle_tip;
        public Geometry.TransformMsg ring1;
        public Geometry.TransformMsg ring2;
        public Geometry.TransformMsg ring3;
        public Geometry.TransformMsg ring_tip;
        public Geometry.TransformMsg pinky0;
        public Geometry.TransformMsg pinky1;
        public Geometry.TransformMsg pinky2;
        public Geometry.TransformMsg pinky3;
        public Geometry.TransformMsg pinky_tip;

        public HandSkeletonMsg()
        {
            this.timestamp = new TimeMsg();
            this.head = new Geometry.TransformMsg();
            this.wrist_root = new Geometry.TransformMsg();
            this.forearm_stub = new Geometry.TransformMsg();
            this.thumb0 = new Geometry.TransformMsg();
            this.thumb1 = new Geometry.TransformMsg();
            this.thumb2 = new Geometry.TransformMsg();
            this.thumb3 = new Geometry.TransformMsg();
            this.thumb_tip = new Geometry.TransformMsg();
            this.index1 = new Geometry.TransformMsg();
            this.index2 = new Geometry.TransformMsg();
            this.index3 = new Geometry.TransformMsg();
            this.index_tip = new Geometry.TransformMsg();
            this.middle1 = new Geometry.TransformMsg();
            this.middle2 = new Geometry.TransformMsg();
            this.middle3 = new Geometry.TransformMsg();
            this.middle_tip = new Geometry.TransformMsg();
            this.ring1 = new Geometry.TransformMsg();
            this.ring2 = new Geometry.TransformMsg();
            this.ring3 = new Geometry.TransformMsg();
            this.ring_tip = new Geometry.TransformMsg();
            this.pinky0 = new Geometry.TransformMsg();
            this.pinky1 = new Geometry.TransformMsg();
            this.pinky2 = new Geometry.TransformMsg();
            this.pinky3 = new Geometry.TransformMsg();
            this.pinky_tip = new Geometry.TransformMsg();
        }

        public HandSkeletonMsg(TimeMsg timestamp, Geometry.TransformMsg head, Geometry.TransformMsg wrist_root, Geometry.TransformMsg forearm_stub, Geometry.TransformMsg thumb0, Geometry.TransformMsg thumb1, Geometry.TransformMsg thumb2, Geometry.TransformMsg thumb3, Geometry.TransformMsg thumb_tip, Geometry.TransformMsg index1, Geometry.TransformMsg index2, Geometry.TransformMsg index3, Geometry.TransformMsg index_tip, Geometry.TransformMsg middle1, Geometry.TransformMsg middle2, Geometry.TransformMsg middle3, Geometry.TransformMsg middle_tip, Geometry.TransformMsg ring1, Geometry.TransformMsg ring2, Geometry.TransformMsg ring3, Geometry.TransformMsg ring_tip, Geometry.TransformMsg pinky0, Geometry.TransformMsg pinky1, Geometry.TransformMsg pinky2, Geometry.TransformMsg pinky3, Geometry.TransformMsg pinky_tip)
        {
            this.timestamp = timestamp;
            this.head = head;
            this.wrist_root = wrist_root;
            this.forearm_stub = forearm_stub;
            this.thumb0 = thumb0;
            this.thumb1 = thumb1;
            this.thumb2 = thumb2;
            this.thumb3 = thumb3;
            this.thumb_tip = thumb_tip;
            this.index1 = index1;
            this.index2 = index2;
            this.index3 = index3;
            this.index_tip = index_tip;
            this.middle1 = middle1;
            this.middle2 = middle2;
            this.middle3 = middle3;
            this.middle_tip = middle_tip;
            this.ring1 = ring1;
            this.ring2 = ring2;
            this.ring3 = ring3;
            this.ring_tip = ring_tip;
            this.pinky0 = pinky0;
            this.pinky1 = pinky1;
            this.pinky2 = pinky2;
            this.pinky3 = pinky3;
            this.pinky_tip = pinky_tip;
        }

        public static HandSkeletonMsg Deserialize(MessageDeserializer deserializer) => new HandSkeletonMsg(deserializer);

        private HandSkeletonMsg(MessageDeserializer deserializer)
        {
            this.timestamp = TimeMsg.Deserialize(deserializer);
            this.head = Geometry.TransformMsg.Deserialize(deserializer);
            this.wrist_root = Geometry.TransformMsg.Deserialize(deserializer);
            this.forearm_stub = Geometry.TransformMsg.Deserialize(deserializer);
            this.thumb0 = Geometry.TransformMsg.Deserialize(deserializer);
            this.thumb1 = Geometry.TransformMsg.Deserialize(deserializer);
            this.thumb2 = Geometry.TransformMsg.Deserialize(deserializer);
            this.thumb3 = Geometry.TransformMsg.Deserialize(deserializer);
            this.thumb_tip = Geometry.TransformMsg.Deserialize(deserializer);
            this.index1 = Geometry.TransformMsg.Deserialize(deserializer);
            this.index2 = Geometry.TransformMsg.Deserialize(deserializer);
            this.index3 = Geometry.TransformMsg.Deserialize(deserializer);
            this.index_tip = Geometry.TransformMsg.Deserialize(deserializer);
            this.middle1 = Geometry.TransformMsg.Deserialize(deserializer);
            this.middle2 = Geometry.TransformMsg.Deserialize(deserializer);
            this.middle3 = Geometry.TransformMsg.Deserialize(deserializer);
            this.middle_tip = Geometry.TransformMsg.Deserialize(deserializer);
            this.ring1 = Geometry.TransformMsg.Deserialize(deserializer);
            this.ring2 = Geometry.TransformMsg.Deserialize(deserializer);
            this.ring3 = Geometry.TransformMsg.Deserialize(deserializer);
            this.ring_tip = Geometry.TransformMsg.Deserialize(deserializer);
            this.pinky0 = Geometry.TransformMsg.Deserialize(deserializer);
            this.pinky1 = Geometry.TransformMsg.Deserialize(deserializer);
            this.pinky2 = Geometry.TransformMsg.Deserialize(deserializer);
            this.pinky3 = Geometry.TransformMsg.Deserialize(deserializer);
            this.pinky_tip = Geometry.TransformMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.head);
            serializer.Write(this.wrist_root);
            serializer.Write(this.forearm_stub);
            serializer.Write(this.thumb0);
            serializer.Write(this.thumb1);
            serializer.Write(this.thumb2);
            serializer.Write(this.thumb3);
            serializer.Write(this.thumb_tip);
            serializer.Write(this.index1);
            serializer.Write(this.index2);
            serializer.Write(this.index3);
            serializer.Write(this.index_tip);
            serializer.Write(this.middle1);
            serializer.Write(this.middle2);
            serializer.Write(this.middle3);
            serializer.Write(this.middle_tip);
            serializer.Write(this.ring1);
            serializer.Write(this.ring2);
            serializer.Write(this.ring3);
            serializer.Write(this.ring_tip);
            serializer.Write(this.pinky0);
            serializer.Write(this.pinky1);
            serializer.Write(this.pinky2);
            serializer.Write(this.pinky3);
            serializer.Write(this.pinky_tip);
        }

        public override string ToString()
        {
            return "HandSkeletonMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nhead: " + head.ToString() +
            "\nwrist_root: " + wrist_root.ToString() +
            "\nforearm_stub: " + forearm_stub.ToString() +
            "\nthumb0: " + thumb0.ToString() +
            "\nthumb1: " + thumb1.ToString() +
            "\nthumb2: " + thumb2.ToString() +
            "\nthumb3: " + thumb3.ToString() +
            "\nthumb_tip: " + thumb_tip.ToString() +
            "\nindex1: " + index1.ToString() +
            "\nindex2: " + index2.ToString() +
            "\nindex3: " + index3.ToString() +
            "\nindex_tip: " + index_tip.ToString() +
            "\nmiddle1: " + middle1.ToString() +
            "\nmiddle2: " + middle2.ToString() +
            "\nmiddle3: " + middle3.ToString() +
            "\nmiddle_tip: " + middle_tip.ToString() +
            "\nring1: " + ring1.ToString() +
            "\nring2: " + ring2.ToString() +
            "\nring3: " + ring3.ToString() +
            "\nring_tip: " + ring_tip.ToString() +
            "\npinky0: " + pinky0.ToString() +
            "\npinky1: " + pinky1.ToString() +
            "\npinky2: " + pinky2.ToString() +
            "\npinky3: " + pinky3.ToString() +
            "\npinky_tip: " + pinky_tip.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
